version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./mysql:/var/lib/mysql
      - ./app/sql_config/conf.d/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    ports:
      - 3306:3306
    networks:
      - db_network
  

  web:
    container_name: django-web
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    networks:
      - db_network

  redis:
    image: redis
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  mysql: