# Generated by Django 4.1.3 on 2023-04-23 06:34

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('name', models.CharField(max_length=20, unique=True)),
                ('des', models.TextField()),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('expiration_date', models.DateTimeField(validators=[api.utils.validate_date])),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small')], max_length=1)),
                ('initial_set', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
