name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: aaa57403/spacup-slep
          stage: main
          yaml: >
            name: sample-web-store-api

            app: dockerfile.v1

            options:
              ports: "3000"
              dockerfile: app/Dockerfile
              commands: |-
                python manage.py makemigrations 
                python manage.py migrate
                python manage.py create_sample_data
                python manage.py runserver 0.0.0.0:3000
              env:
                - name: SECRET_KEY
                  value: django-insecure-nekkd7f8#7!-j6!q%4nlr)xp+m!!w%q(92_=jtniq%m*4*2^xc
                - name: DJANGO_ALLOWED_HOSTS
                  value: "*"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: dockerfile
